## numpy universal functions are fast one-sweep operations for arrays
1.  They are instances of the numpy.ufunc class. Many of which are implemented in compiled C code.
2.  There are over 60 ufuncs in numpy 1.7.  We will focus on the math ones here. 
3.  You can define custom ufunc instances using the frompyfunc factory function

In [2]:
import numpy as np

<a id= 'back-to-top'></a>

Math operations


- add(x1, x2, /[, out, where, casting, order, …]) Add arguments element-wise. 


- subtract(x1, x2, /[, out, where, casting, …])对应元素相
Subtract arguments, element-wise.


- multiply(x1, x2, /[, out, where, casting, …]) 对应元素相乘
Multiply arguments element-wise.


- divide(x1, x2, /[, out, where, casting, …]) 对应元素相除
Returns a true division of the inputs, element-wise.


- logaddexp(x1, x2, /[, out, where, casting, …])
Logarithm of the sum of exponentiations of the inputs.


- logaddexp2(x1, x2, /[, out, where, casting, …])
Logarithm of the sum of exponentiations of the inputs in base-2.


- true_divide(x1, x2, /[, out, where, …])
Returns a true division of the inputs, element-wise.


- floor_divide(x1, x2, /[, out, where, …]) 对应元素相除，对返回值取整
Return the largest integer smaller or equal to the division of the inputs. 


- negative(x, /[, out, where, casting, order, …]) 
Numerical negative, element-wise.


- positive(x, /[, out, where, casting, order, …])
Numerical positive, element-wise.


- power(x1, x2, /[, out, where, casting, …])
First array elements raised to powers from second array, element-wise.


- remainder(x1, x2, /[, out, where, casting, …]) 余数
Return element-wise remainder of division.


- mod(x1, x2, /[, out, where, casting, order, …])
Return element-wise remainder of division.


- fmod(x1, x2, /[, out, where, casting, …])
Return the element-wise remainder of division.


- divmod(x1, x2[, out1, out2], / [[, out, …])
Return element-wise quotient and remainder simultaneously.


- absolute(x, /[, out, where, casting, order, …])
Calculate the absolute value element-wise.


- fabs(x, /[, out, where, casting, order, …])
Compute the absolute values element-wise.


- rint(x, /[, out, where, casting, order, …])
Round elements of the array to the nearest integer.


- sign(x, /[, out, where, casting, order, …])
Returns an element-wise indication of the sign of a number.


- heaviside(x1, x2, /[, out, where, casting, …])
Compute the Heaviside step function.


- conj(x, /[, out, where, casting, order, …])
Return the complex conjugate, element-wise.


- exp(x, /[, out, where, casting, order, …])
Calculate the exponential of all elements in the input array.


- exp2(x, /[, out, where, casting, order, …])
Calculate 2**p for all p in the input array.


- log(x, /[, out, where, casting, order, …])
Natural logarithm, element-wise.

ufunc is super convenient because it does not need loops to things that are very intuitive to us, such as operations element-to-element. 

In [9]:
#np.arange(start, stop, step)
a = np.arange(10,15,2)
a

array([10, 12, 14])

In [15]:
b= np.array([5,6,7])
b

array([5, 6, 7])

In [12]:
a/b

array([2., 2., 2.])

In [14]:
a*b

array([50, 72, 98])

## 加法
It is addition with broadcasting/sharing. 

In [17]:
np.add(1,4)

5

In [27]:
# We can also do this. 
1+4

5

In [20]:
a =np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
b = np.arange(3)
b

array([0, 1, 2])

In [30]:
a+b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [23]:
np.add(a,b)

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

## 减法

In [24]:
np.subtract(1,4)

-3

In [25]:
# We can also do this. 
1-4

-3

In [28]:
# But the magic is the following
a - b

array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6]])

In [29]:
np.subtract(a,b)

array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6]])

In [39]:
np.subtract?

## 乘法

In [31]:
2*4

8

In [32]:
np.multiply(2,4)

8

In [36]:
# Remember what a is?
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
# Remember what b is?
b

array([0, 1, 2])

In [38]:
# it seems that the first column of b got shared by the first column of a, and so on. 
a*b

array([[ 0,  1,  4],
       [ 0,  4, 10],
       [ 0,  7, 16]])

## 除法  

In [41]:
a/(b+1)

array([[0.        , 0.5       , 0.66666667],
       [3.        , 2.        , 1.66666667],
       [6.        , 3.5       , 2.66666667]])